name: pypepper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.17
  - pip=25.0.1
  - pip:
      - arrow==1.3.0
      - cachetools==5.5.1
      - cryptography==44.0.1
      - fastapi==0.115.8
      - uvicorn==0.34.0
      - loguru==0.7.3
      - mongoengine==0.29.1
      - python-box==7.3.2
      - pymysql==1.1.1
      - pyyaml==6.0.2
      - sqlalchemy==2.0.38
      - coverage==7.6.12
      - pytest==8.3.4
      - pytest-asyncio==0.25.3
      - pytest-cov==6.0.0
      - build==1.2.2.post1
      - twine==6.1.0
