[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pypepper"
version = "0.2.0"
authors = [
    { name = "jovijovi", email = "mageyul@hotmail.com" },
]
description = "PyPepper is a microservice toolkit written in Python."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/jovijovi/pypepper"
"Bug Tracker" = "https://github.com/jovijovi/pypepper/issues"
