[pytest]
addopts =
    --cache-clear
    --strict-markers
    -s
testpaths =
    tests
log_cli = true
python_files = test_*.py
markers =
    requires_postgres: needs local PostgreSQL from devenv/ci.yaml
    requires_mysql: needs local MySQL from devenv/ci.yaml
    requires_mongodb: needs local MongoDB from devenv/ci.yaml
