version: '3.1'

networks:
  devenv-network-pypedro:

services:
  mysql:
    container_name: devenv_mysql_pypedro
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ../.database/mysql_data:/var/lib/mysql
      - ./init/mysql/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./init/mysql/table.sql:/docker-entrypoint-initdb.d/2_table.sql
    ports:
      - "3306:3306"
    networks:
      - devenv-network-pypedro
