version: '3.1'

networks:
  devenv-network-pypedro:

services:
  mysql:
    container_name: devenv_mysql_pypedro
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ../.database/mysql_data:/var/lib/mysql
      - ./init/mysql/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./init/mysql/table.sql:/docker-entrypoint-initdb.d/2_table.sql
    ports:
      - "3306:3306"
    networks:
      - devenv-network-pypedro

  mongo:
    container_name: devenv_mongodb_congress
    image: mongo:5.0.14
    command: --auth
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
    volumes:
      - ../.database/mongodb_data:/data/db
      - ./init/mongodb/user.js:/docker-entrypoint-initdb.d/1_user.js
    ports:
      - "27017:27017"
    networks:
      - devenv-network-pypedro

  mongo-express:
    container_name: devenv_mongo_express_congress
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - devenv-network-pypedro
