#!/usr/bin/env python3
"""Generate docs/INDEX.md from per-file YAML frontmatter.

Part of PyPepper's Lithos adoption (single full-lifecycle governance model).
Scans every ``docs/**/*.md`` file for a YAML frontmatter block delimited by
``---`` lines, validates required fields (title, status, created_at), and
writes / checks ``docs/INDEX.md`` grouped by status. The index is the generated
docs-directory catalogue of the knowledge spine; root entry points such as
``README.md``, ``GOAL.md``, and ``LESSONS.md`` stay outside it.

Usage::

    python scripts/build_docs_index.py --write   # regenerate docs/INDEX.md
    python scripts/build_docs_index.py --check    # fail if the on-disk index is stale
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = PROJECT_ROOT / "docs"
INDEX_PATH = DOCS_ROOT / "INDEX.md"

VALID_STATUSES = {"active", "archived", "superseded", "deprecated"}
REQUIRED_FIELDS = ("title", "status", "created_at")
DATE_REQUIRED_STATUSES = {"archived", "superseded", "deprecated"}
# Generated artifacts stay out of the indexed corpus.
SKIP_RELATIVE = frozenset({"INDEX.md", "lessons/_drift_report.md"})


def _parse_frontmatter(text: str) -> dict | None:
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end < 0:
        return None
    block = text[4:end].splitlines()
    data: dict = {}
    current_list_key: str | None = None
    for line in block:
        if not line.strip():
            current_list_key = None
            continue
        if line.startswith("  - ") and current_list_key is not None:
            data[current_list_key].append(line[4:].strip().strip('"').strip("'"))
            continue
        match = re.match(r"^([\w_]+):\s*(.*)$", line)
        if not match:
            current_list_key = None
            continue
        key, value = match.group(1), match.group(2).strip()
        if not value:
            data[key] = []
            current_list_key = key
            continue
        data[key] = value.strip('"').strip("'")
        current_list_key = None
    return data


def _validate(rel: str, fm: dict) -> list[str]:
    errors: list[str] = []
    for field in REQUIRED_FIELDS:
        if field not in fm or not fm[field]:
            errors.append(f"{rel}: missing required field {field!r}")
    status = fm.get("status", "")
    if status and status not in VALID_STATUSES:
        errors.append(f"{rel}: invalid status {status!r} (allowed: {sorted(VALID_STATUSES)})")
    if status in DATE_REQUIRED_STATUSES and not fm.get("archived_at"):
        errors.append(f"{rel}: status={status} requires archived_at")
    return errors


def _scan() -> tuple[list[tuple[str, dict]], list[str]]:
    docs: list[tuple[str, dict]] = []
    errors: list[str] = []
    if not DOCS_ROOT.is_dir():
        errors.append(f"docs root not found: {DOCS_ROOT}")
        return docs, errors
    for path in sorted(DOCS_ROOT.rglob("*.md")):
        rel = path.relative_to(DOCS_ROOT).as_posix()
        if rel in SKIP_RELATIVE:
            continue
        text = path.read_text(encoding="utf-8")
        fm = _parse_frontmatter(text)
        if fm is None:
            errors.append(f"{rel}: no YAML frontmatter block")
            continue
        errors.extend(_validate(rel, fm))
        docs.append((rel, fm))
    return docs, errors


def _render(docs: list[tuple[str, dict]]) -> str:
    by_status: dict[str, list[tuple[str, dict]]] = defaultdict(list)
    for rel, fm in docs:
        by_status[str(fm.get("status", "unknown"))].append((rel, fm))
    for entries in by_status.values():
        entries.sort(key=lambda item: str(item[1].get("created_at", "")), reverse=True)
    out: list[str] = [
        "<!-- AUTO-GENERATED by scripts/build_docs_index.py — do not hand-edit -->",
        "",
        "# Documentation Index",
        "",
        f"Total: {len(docs)} documents tracked across {len(by_status)} statuses.",
        "",
    ]
    for status in ("active", "archived", "superseded", "deprecated"):
        entries = by_status.get(status, [])
        if not entries:
            continue
        out.append(f"## {status.capitalize()} ({len(entries)})")
        out.append("")
        for rel, fm in entries:
            title = str(fm.get("title", rel)).strip()
            created = str(fm.get("created_at", ""))
            out.append(f"- [{title}]({rel}) — created {created}")
        out.append("")
    for status in sorted(set(by_status) - {"active", "archived", "superseded", "deprecated"}):
        entries = by_status[status]
        out.append(f"## {status.capitalize()} ({len(entries)})")
        out.append("")
        for rel, fm in entries:
            out.append(f"- [{fm.get('title', rel)}]({rel})")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write docs/INDEX.md")
    parser.add_argument("--check", action="store_true", help="check that the on-disk index is up to date")
    args = parser.parse_args()
    if not args.write and not args.check:
        args.write = True
    docs, errors = _scan()
    if errors:
        for line in errors:
            print(f"ERROR: {line}", file=sys.stderr)
        return 2
    rendered = _render(docs)
    if args.check:
        existing = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
        if existing != rendered:
            print(
                "ERROR: docs/INDEX.md is out of date. "
                "Run `python scripts/build_docs_index.py --write` and commit.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {len(docs)} docs in sync with INDEX.md")
        return 0
    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {INDEX_PATH} ({len(docs)} docs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
